# site settings
title: Samuel Ledesma Holt
subtitle: Portfolio and Resume
email: samuel.l.holt@gmail.com
description: 
baseurl:  # the subpath of your site, e.g. /blog
url: https://sammyholt.com/ # the base hostname & protocol for your site
author: Samuel Ledesma Holt
#street_address: 1234 Somewhere Road
#city: Nashville
#state: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/sammyholt
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/samuellholt/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
